name: book_flip
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/gabbygreat/book_flip

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
